# Generated by Django 5.1.5 on 2025-01-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0002_guitar_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
