# Generated by Django 5.1.5 on 2025-01-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0003_alter_guitar_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
