# Generated by Django 5.1.5 on 2025-01-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0004_alter_guitar_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitar',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='guitar',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='guitars/avatars/'),
        ),
    ]
