# Generated by Django 5.1.5 on 2025-01-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0005_guitar_description_alter_guitar_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
